#!/usr/bin/env node
// Turns a single-file HTML export (everything inlined as base64 data: URLs) into a normal page:
//   - documents embedded in links  → real pages at /<route>/<name>/ (browsers refuse to open data: links)
//   - images, fonts, video, audio  → src/assets/<route>/, which Vite hashes and Vercel caches for a year
//   - other linked files (PDF …)   → public/<route>/files/
// The export stays the source of truth: to update a page, re-run this on the new export.
//
//   npm run unpack -- <export.html> <route> [--force]
//
// Document pages are named from their <title>. To give one a different URL, map the generated name to
// the one you want in scripts/unpack-names.json and re-run; the mapping is reused on every later run.
//
// Each run replaces <route>/, src/assets/<route>/ and public/<route>/files/, and only ever deletes
// folders it generated. --force is only needed once, to replace a <route>/index.html added by hand.

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SITE = "https://www.rapsap.com";
const MIN_ASSET_BYTES = 2048; // smaller images stay inline: a request would cost more than the bytes
const MARKER = "<!-- Generated by scripts/unpack-html.mjs: edit the export and re-run, not this file -->";
const STAMP = ".generated-by-unpack-html";
const EXTENSIONS = {
  "image/webp": "webp", "image/png": "png", "image/jpeg": "jpg", "image/gif": "gif", "image/avif": "avif",
  "image/svg+xml": "svg", "image/x-icon": "ico", "image/vnd.microsoft.icon": "ico",
  "font/woff2": "woff2", "font/woff": "woff", "font/ttf": "ttf", "font/otf": "otf",
  "video/mp4": "mp4", "video/webm": "webm", "audio/mpeg": "mp3", "audio/ogg": "ogg", "application/pdf": "pdf",
};
const STOP_WORDS = new Set(["a", "an", "and", "the", "of", "for", "to", "in", "on", "with", "at", "its", "by"]);
const DATA_URL = /data:([a-z]+\/[a-z0-9.+-]+)((?:;[a-z-]+=[^;,"')\s]+)*);base64,([A-Za-z0-9+/=]+)/gi;
// Folders a route must never be, because the site or this script already uses them
const RESERVED = new Set(["src", "public", "partials", "scripts", "node_modules", "dist", "assets", "fonts", "image-assets"]);

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const force = args.includes("--force");
const [input, route] = args.filter((a) => a !== "--force");

if (!input || !route) fail("Usage: npm run unpack -- <export.html> <route> [--force]");
if (!/^[a-z0-9-]+$/.test(route)) fail(`Route must be lowercase letters, digits and dashes, e.g. "aaharank" (got "${route}")`);
if (RESERVED.has(route)) fail(`"${route}" is used by the site itself; pick another route.`);
if (!existsSync(input)) fail(`File not found: ${input}`);

const pageDir = resolve(root, route);
const assetDir = resolve(root, "src/assets", route);
const fileDir = resolve(root, "public", route, "files");
const existing = resolve(pageDir, "index.html");
if (existsSync(existing) && !readFileSync(existing, "utf8").includes(MARKER) && !force)
  fail(`${route}/index.html exists and was not generated by this script. Re-run with --force to replace it.`);
for (const dir of [assetDir, fileDir])
  if (existsSync(dir) && !existsSync(resolve(dir, STAMP)))
    fail(`${dir.replace(root + "/", "")}/ already holds files this script didn't create; pick another route.`);

const namesFile = resolve(root, "scripts/unpack-names.json");
const names = (existsSync(namesFile) ? JSON.parse(readFileSync(namesFile, "utf8")) : {})[route] ?? {};

const slugify = (text, maxWords) =>
  text.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim().split(" ")
    .filter((w) => w && !STOP_WORDS.has(w)).slice(0, maxWords).join("-");

// Names files after what they are (alt text, font family, document title) instead of a hash
function describe(html, index, mime, bytes) {
  if (mime === "text/html") {
    const title = bytes.toString("utf8").match(/<title>([\s\S]*?)<\/title>/i)?.[1] ?? "";
    // "Site — Section: Topic" → "topic"
    return slugify(title.split(/\s[—|]\s/).pop().split(":").pop(), 4) || "document";
  }
  const tagStart = html.lastIndexOf("<", index);
  const tag = html.slice(tagStart, html.indexOf(">", index) + 1);
  const alt = /^<img\b/i.test(tag) && tag.match(/\salt="([^"]*)"/i)?.[1];
  if (alt) return slugify(alt, 5);
  const download = /^<a\b/i.test(tag) && tag.match(/\sdownload="([^"]*)"/i)?.[1];
  if (download) return slugify(download.replace(/\.[a-z0-9]+$/i, ""), 5);
  const fontFace = html.lastIndexOf("@font-face", index);
  if (mime.startsWith("font/") && fontFace > index - 400)
    return slugify(html.slice(fontFace, index).match(/font-family:\s*['"]?([^;'"]+)/i)?.[1] ?? "", 4);
  return "";
}

const pages = new Map(); // hash → { name, slug, html }
const assets = new Map(); // hash → { name, bytes, mime, inLink, dir, file, url }
const usedNames = new Set();
const slugs = new Set();
const report = [];
const warnings = [];

function uniqueName(base, ext) {
  let name = `${base}.${ext}`;
  for (let i = 2; usedNames.has(name); i++) name = `${base}-${i}.${ext}`;
  usedNames.add(name);
  return name;
}

function uniqueSlug(base) {
  let slug = base;
  for (let i = 2; slugs.has(slug); i++) slug = `${base}-${i}`;
  slugs.add(slug);
  return slug;
}

function unpack(html, label) {
  // Vite rewrites file paths everywhere in HTML except inside <script>, so files there stay inline
  const scripts = [...html.matchAll(/<script\b[\s\S]*?<\/script>/gi)].map((m) => [m.index, m.index + m[0].length]);
  const inScript = (i) => scripts.some(([start, end]) => i > start && i < end);

  // First pass: give each distinct file the best name any of its occurrences offers
  const found = [...html.matchAll(DATA_URL)].filter((m) => !inScript(m.index)).map((m) => {
    const [whole, mime, , b64] = m;
    const at = m.index;
    const bytes = Buffer.from(b64, "base64");
    const hash = createHash("sha256").update(bytes).digest("hex").slice(0, 8);
    const inLink = /<a\b[^>]*\shref=["']?$/i.test(html.slice(Math.max(0, m.index - 300), m.index));
    const type = mime.toLowerCase();
    return { whole, at, mime: type, bytes, hash, inLink, name: describe(html, at, type, bytes) };
  });
  for (const f of found) {
    if (f.mime === "text/html") {
      if (!pages.has(f.hash)) pages.set(f.hash, { name: f.name, slug: null, html: f.bytes.toString("utf8") });
    } else if (EXTENSIONS[f.mime] && (f.inLink || f.bytes.length >= MIN_ASSET_BYTES)) {
      const a = assets.get(f.hash) ?? { name: "", bytes: f.bytes, mime: f.mime, inLink: f.inLink };
      a.name ||= f.name;
      a.inLink ||= f.inLink;
      assets.set(f.hash, a);
    }
  }

  // Second pass: give each file its URL, then swap every occurrence for it
  for (const p of pages.values()) {
    if (p.slug) continue;
    p.slug = uniqueSlug(names[p.name] ?? p.name);
    p.html = finishPage(unpack(p.html, `${route}/${p.slug}`), `${route}/${p.slug}`);
  }
  for (const [hash, a] of assets) {
    if (a.url) continue;
    a.file = uniqueName(a.name || `${a.mime.split("/")[0]}-${hash}`, EXTENSIONS[a.mime]);
    // Vite doesn't rewrite <a href>, so link targets go to public/ and keep a fixed URL
    a.dir = a.inLink ? fileDir : assetDir;
    a.url = a.inLink ? `/${route}/files/${a.file}` : `/src/assets/${route}/${a.file}`;
  }
  // Swap by position, not by text: the same file can also appear inside a <script>, which must stay as is
  let out = "";
  let last = 0;
  for (const f of found) {
    const target = f.mime === "text/html" ? `/${route}/${pages.get(f.hash).slug}/` : assets.get(f.hash)?.url;
    if (!target) continue;
    out += html.slice(last, f.at) + target;
    last = f.at + f.whole.length;
  }
  out += html.slice(last);

  const kept = found.filter((f) => f.mime !== "text/html" && !assets.has(f.hash)).length;
  const skipped = [...html.matchAll(DATA_URL)].length - found.length;
  report.push(
    `${label}: ${found.length - kept} embedded file(s) moved out` +
      (kept ? `, ${kept} small or unknown one(s) left inline` : "") +
      (skipped ? `, ${skipped} inside <script> left inline` : ""),
  );
  check(out, label);
  return out;
}

// Things the script can't fix by itself, so a person should look at them
function check(html, label) {
  const broken = html.match(/<a\b[^>]*\shref=["']?data:[^"'\s>]{0,40}/gi);
  if (broken) warnings.push(`${label}: ${broken.length} link(s) still open a data: URL, which browsers block (not base64, or an unknown type)`);
  const relative = [...html.matchAll(/\s(?:href|src)=["']?(?!\/|#|[a-z][a-z0-9+.-]*:)([^"'\s>]+)/gi)].map((m) => m[1]);
  if (relative.length) warnings.push(`${label}: relative link(s) that pointed next to the export file: ${[...new Set(relative)].slice(0, 5).join(", ")}`);
  if (/<meta\b[^>]*(og|twitter):image[^>]*content=["']?\/src\//i.test(html))
    warnings.push(`${label}: og/twitter:image was embedded; social previews need an absolute https:// URL there`);
}

// Browsers show a stray "<" (as in "< 5" or "<25g") as text, but Vite's HTML parser fails the build on it
const escapeStrayLessThan = (html) =>
  html
    .split(/(<(script|style|textarea)\b[\s\S]*?<\/\2>)/i)
    .map((part, i) => (i % 3 === 0 ? part.replace(/<(?![a-zA-Z/!?])/g, "&lt;") : i % 3 === 1 ? part : ""))
    .join("");

function finishPage(html, path) {
  let out = escapeStrayLessThan(html).replace(/^(\s*<!doctype html>)/i, `$1\n${MARKER}`);
  if (!out.includes(MARKER)) out = `${MARKER}\n${out}`;
  if (!/rel=["']?canonical/i.test(out))
    out = out.replace(/<\/head>/i, `<link rel="canonical" href="${SITE}/${path}/">\n</head>`);
  // Inline fonts used to arrive with the HTML; preload the extracted ones so text doesn't render late
  const fonts = new Map([...out.matchAll(/url\(['"]?(\/src\/assets\/[^'")]+\.(woff2?|ttf|otf))['"]?\)/g)].map((m) => [m[1], m[2]]));
  const preloads = [...fonts].map(([url, ext]) => `<link rel="preload" href="${url}" as="font" type="font/${ext}" crossorigin>`).join("");
  if (preloads) out = out.replace(/<style\b/i, `${preloads}\n$&`);
  return out;
}

const page = finishPage(unpack(readFileSync(input, "utf8"), route), route);

for (const [from, to] of Object.entries(names))
  if (![...pages.values()].some((p) => p.name === from))
    warnings.push(`scripts/unpack-names.json: "${from}" → "${to}" matched no document (did its title change?)`);

rmSync(pageDir, { recursive: true, force: true });
rmSync(assetDir, { recursive: true, force: true });
rmSync(fileDir, { recursive: true, force: true });
mkdirSync(pageDir, { recursive: true });
writeFileSync(resolve(pageDir, "index.html"), page);
for (const p of pages.values()) {
  mkdirSync(resolve(pageDir, p.slug), { recursive: true });
  writeFileSync(resolve(pageDir, p.slug, "index.html"), p.html);
}
for (const a of assets.values()) {
  mkdirSync(a.dir, { recursive: true });
  writeFileSync(resolve(a.dir, STAMP), "");
  writeFileSync(resolve(a.dir, a.file), a.bytes);
}

// Keep the sitemap in step: add new pages, drop ones this route no longer has
const sitemap = resolve(root, "public/sitemap.xml");
const urls = [route, ...[...pages.values()].map((p) => `${route}/${p.slug}`)].map((p) => `${SITE}/${p}/`);
if (existsSync(sitemap)) {
  let xml = readFileSync(sitemap, "utf8");
  const today = new Date().toISOString().slice(0, 10);
  const entry = /\n?[ \t]*<url>\s*<loc>([^<]+)<\/loc>[\s\S]*?<\/url>/g;
  const gone = [...xml.matchAll(entry)].map((m) => m[1]).filter((u) => u.startsWith(`${SITE}/${route}/`) && !urls.includes(u));
  xml = xml.replace(entry, (m, loc) => (gone.includes(loc) ? "" : m));
  const added = urls.filter((u) => !xml.includes(`<loc>${u}</loc>`));
  xml = xml.replace("</urlset>", added.map((u) => `  <url>\n    <loc>${u}</loc>\n    <lastmod>${today}</lastmod>\n  </url>\n`).join("") + "</urlset>");
  writeFileSync(sitemap, xml);
  if (added.length) report.push(`sitemap: added ${added.join(", ")}`);
  if (gone.length) warnings.push(`sitemap: removed ${gone.join(", ")}. If those URLs were ever live, add redirects in public/staticwebapp.config.json.`);
}

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
console.log(`\nUnpacked ${input} (${kb(readFileSync(input).length)}) → /${route}/ (${kb(Buffer.byteLength(page))})\n`);
console.log("Pages:");
for (const u of urls) console.log(`  ${u.replace(SITE, "")}`);
console.log("Files:");
for (const a of assets.values()) console.log(`  ${a.url}  ${kb(a.bytes.length)}`);
console.log(`\n${report.join("\n")}\n`);
if (warnings.length) console.log(`Check these:\n${warnings.map((w) => `  ! ${w}`).join("\n")}\n`);

function fail(message) {
  console.error(message);
  process.exit(1);
}
